---
title: ""
---

```{r setup, include=FALSE}

knitr::opts_chunk$set( echo = TRUE )

```

<br>

## Preface

<br>

Welcome to the [Social Network Analysis Textbook](https://jacobtnyoung.github.io/sna-textbook/)!  

This textbook is designed to introduce you to basic concepts used in social network analysis (SNA). The textbook is divided into chapters that cover a variety of these concepts. The textbook is not exhaustive, but most of the major topics are discussed.

For those readers who are new to SNA, I would suggest starting at the beginning (i.e., [Chapter 1](ch-01-intro-to-sna.html)) and working through in chronological order. For those readers who are already familiar with SNA, feel free to skip through the chapters (see the Table of Contents below).

<br>

## Table of Contents

<br>

#### [*Chapter 1: Introduction to Social Network Analysis*](ch-01-intro-to-sna.html)

#### [*Chapter 2: Social Network Analysis and Theory*](ch-02-sna-theory.html)

#### [*Chapter 3: Social Network Analysis and Methods for Data Collection*](ch-03-sna-methods.html)

#### [*Chapter 4: Network Data Structures*](ch-04-net-data-structures.html)

#### [*Chapter 5: Degree Centrality*](ch-05-centrality-degree.html)

#### [*Chapter 6: Closeness Centrality*](ch-06-centrality-closeness.html)

#### [*Chapter 7: Betweenness Centrality*](ch-07-centrality-betweenness.html)

#### [*Chapter 8: Comparison of Centrality Measures*](ch-08-centrality-comparison.html)

#### [*Chapter 9: Local Structure*](ch-09-local-structure.html)

#### [*Chapter 10: Bipartite Graphs/Two-Mode Networks*](ch-10-bipartite-graphs.html)

#### [*Chapter 11: Projection*](ch-11-projection.html)

#### [*Chapter 12: Weighted Graphs*](ch-12-weighted-graphs.html)

<br><br>

***Please*** report any corrections or comments to the [Issues](https://github.com/jacobtnyoung/sna-textbook/issues) page. Thanks!

<br><br>